name: Validate

on:
  push:
  pull_request:
  # Draai de check ook elke nacht om 00:00 om te checken op nieuwe regels
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# Beveiliging: geef de actie alleen leesrechten
permissions:
  contents: read

jobs:
  # JOB 1: HACS Validatie (Structuur & Metadata)
  validate-hacs:
    runs-on: "ubuntu-latest"
    name: HACS Validation
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"

  # JOB 2: Hassfest Validatie (Code & JSON regels van Home Assistant)
  validate-hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest Validation
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Hassfest Action
        uses: "home-assistant/actions/hassfest@master"
